### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by wale13** [wale13/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by wale14** [comment]
— Hello! I'm a beginner frontend developer. At present time I study hard to became a pro in JavaScript, Angular and related technologies. I am a calm, non-conflict person, but I love to joke sometimes :) .
