### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by wale13** [wale13/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by wale14** [comment]
Feb 01 2010 – Sep 30 2017
CEO at Private Enterprise “Korporraciya Shchastya”
(I managed an enterprise that was engaged in import and wholesale trade.)
Nov 14 2008 - forever
Married Nadiya Hervazyuk
Jun 25 2007 – Jun 01 2009
Main specialist at Pension Fund of Ukraine
(In fact, I acted as a system administrator in one of district department. My responsibilities included
maintaining the health of servers and workstations, managing networks, etc.)
Jul 21 1986
Born in Lviv, Ukraine
