### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by wale13** [wale13/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by wale14** [comment]
**SKILLS**
HTML CSS JS JQUERY ANGULAR NODEJS NPM SQLITE SQL BOOTSTRAP MICROSOFT OFFICE WINDOWS

**CHARACTER**
Awesome guy!

**LANGUAGES**
🇺🇦 УКРАЇНСЬКА 🇷🇺 РУССКИЙ 🇺🇸 ENGLISH

**EDUCATION**
Jul 18 2018 – till now Self-study
Jun 18 2018 – Jul 18 2018 SoftServe University:
Completed the HTML5 App Development Fundamentals (HTML5/CSS3/JavaScript) course.
2002 – 2007 Lviv Commercial Academy:
Economic Cybernetics Specialist Degree.
1992 – 2002 School.

**INTERESTS**
Computer/IT technologies
Cycling
Travelling
Photography
